version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - HOST=0.0.0.0
      - LANG=C.UTF-8
      - EDITOR=vim
    ports:
      - "${EXTERNAL_RAILS_PORT:-3000}:3000"
      - "${EXTERNAL_WEBPACKER_PORT:-3035}:3035"
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
  db:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tty: true
    ports:
      - "${EXTERNAL_POSTGRES_PORT:-5432}:5432"

volumes:
  postgres_data:
  bundle:
  node_modules:
